---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: campanify.it
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-be4b10c4
  image_type: m1.small
  image_id: ami-eafa5883
  security_groups:
  - campanify-web_production_default
  - campanify-web_production_web
  - campanify-web_production_web_tools
  - campanify-web_production_production
  - campanify-web_production_app
  - campanify-web_production_passenger_nginx
  - campanify-web_production_collectd
  - campanify-web_production_common
  - campanify-web_production_monit
  - campanify-web_production_db
  - campanify-web_production_postgresql
  - campanify-web_production_postgresql_master
  - campanify-web_production_examples
  - campanify-web_production_graphite_server
  - campanify-web_production_graphite_web
  - campanify-web_production_haproxy
  external_host: ec2-23-22-194-158.compute-1.amazonaws.com
  external_ip: 23.22.194.158
  internal_host: ip-10-4-118-4.ec2.internal
  internal_ip: 10.4.118.4
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
